In [1]:
import pandas as pd

df = pd.read_csv('games.csv')

In [2]:
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 125855 entries, 2539430 to 4247310
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125854 non-null  str
 1   Name                        125855 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  int64
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  float64
 6   Price                       125855 non-null  int64
 7   DiscountDLC count           125855 non-null  int64
 8   About the game              117393 non-null  str
 9   Supported languages         125855 non-null  str
 10  Full audio languages        125855 non-null  str
 11  Reviews                     12181 non-null   str
 12  Header image                125774 non-null  str
 13  Website                     50520 non-null   str
 14  Support url                 55295 non-null   str
 15  Support email               103225 non-null  str
 16  Windows                     125855 non-null  bool
 17  Mac                         125855 non-null  bool
 18  Linux                       125855 non-null  bool
 19  Metacritic score            125855 non-null  int64
 20  Metacritic url              4258 non-null    str
 21  User score                  125855 non-null  int64
 22  Positive                    125855 non-null  int64
 23  Negative                    125855 non-null  int64
 24  Score rank                  40 non-null      float64
 25  Achievements                125855 non-null  int64
 26  Recommendations             125855 non-null  int64
 27  Notes                       23310 non-null   str
 28  Average playtime forever    125855 non-null  int64
 29  Average playtime two weeks  125855 non-null  int64
 30  Median playtime forever     125855 non-null  int64
 31  Median playtime two weeks   125855 non-null  int64
 32  Developers                  117406 non-null  str
 33  Publishers                  116933 non-null  str
 34  Categories                  116889 non-null  str
 35  Genres                      117432 non-null  str
 36  Tags                        83353 non-null   str
 37  Screenshots                 119828 non-null  str
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), str(19)
memory usage: 35.9 MB

In [4]:
kolom_dipilih = [
    'AppID','Name',
    'Peak CCU',
    'Positive','Negative',
    'Price','Release date', 'Genres',
    'Categories','Developers','Publishers',
    'Required age'
]
df_sub = df[kolom_dipilih].copy()

df_clean = df_sub.dropna()

df_sample = df_clean.sample(n=500, random_state=42)

df_sample.to_csv('games_sample_500.csv', index=False)

print("Total Baris tersimpan:", len(df_sample))
df_sample.head()

Total Baris tersimpan: 500

,AppID,Name,Peak CCU,Positive,Negative,Price,Release date,Genres,Categories,Developers,Publishers,Required age
2499710,アパシー学校であった怖い話 Visual Novel Version,"Aug 7, 2023",0,4,0,0,0 - 20000,Adventure,"Single-player,Family Sharing","七転び八転がり,SHANNON",七転び八転がり,8.99
2952200,Merge,"Aug 1, 2024",0,0,0,0,0 - 20000,"Casual,Indie","Single-player,Steam Achievements,Family Sharing",Rome Renner,Rome Renner,1.99
3778870,Powwow Bound: A Menominee Homecoming,"Nov 18, 2025",0,0,0,0,0 - 0,"Adventure,Casual,Free To Play","Single-player,Steam Achievements,Full controll...","Nebraska Public Media,PBS Wisconsin",Nebraska Public Media,0.00
1512070,VR Hiroshima 1945,"Jan 15, 2021",0,17,14,68,0 - 20000,Adventure,"Single-player,Tracked Controller Support,VR On...",William of Oxford,William of Oxford,1.59
15300,Tom Clancy's Ghost Recon®,"Jul 15, 2008",17,1400,115,0,200000 - 500000,Action,"Single-player,Multi-player,Co-op,Family Sharing",Red Storm Entertainment,Ubisoft,2.99